### ISSUE TITLE
Error with Using Ahead of Time(AOT) Compilation

### ISSUE THREAD

**Issue by MarkSky** [LostBeard/BlazorWASMSIMDDetectExample#2]
I just add `<RunAOTCompilation>true</RunAOTCompilation>` in the .csproj file.

After building and pushing to IIS, I open it on Safari in iPhone 7 Plus.

I couldn't open the web and got some errors.
<img width="1208" alt="截圖 2023-12-11" src="https://github.com/LostBeard/BlazorWASMSIMDDetectExample/assets/4032734/ab80b3ef-409a-421c-8500-06788ac2ed42">

**Comment by LostBeard** [comment]
OpCode 253 aka 0xFD is a WASM SIMD opcode according to [WebAssembly OpCodes](https://pengowray.github.io/wasm-ops/) (section 'SIMD opcodes (Vector instructions)'). 

It looks like the failing dotnet Javacsript file is loading from your ```_frameworkCompat/``` folder so maybe your build compat. is not building without SIMD? 

I am not sure how AOT affects SIMD in the build.

**Comment by LostBeard** [comment]
I have updated the repo project to enable AOT via the ```<RunAOTCompilation>``` flag and it is still working on my devices that do not support SIMD.

It appears the RunAOTCompilation flag is not causing the issue. It is likely your _frameworkCompat build (the ReleaseCompat configuration) is being built with SIMD enabled. Verify you have added the code below to your project .csproj and that your publish script is using the flag ```--configuration ReleaseCompat``` for your compat build step.

```xml
<PropertyGroup>
    <Configurations>Debug;Release;ReleaseCompat</Configurations>
</PropertyGroup>

<PropertyGroup Condition=" '$(Configuration)' == 'ReleaseCompat' ">
	<WasmEnableSIMD>false</WasmEnableSIMD>
	<BlazorWebAssemblyJiterpreter>false</BlazorWebAssemblyJiterpreter>
</PropertyGroup>
```

Can you share your publish script and your project .csproj file?

**Comment by LostBeard** [comment]
Can you test this repos [demo site](https://lostbeard.github.io/BlazorWASMSIMDDetectExample/) with your device?

**Comment by MarkSky** [comment]
> I have updated the repo project to enable AOT via the `<RunAOTCompilation>` flag and it is still working on my devices that do not support SIMD.
> 
> It appears the RunAOTCompilation flag is not causing the issue. It is likely your _frameworkCompat build (the ReleaseCompat configuration) is being built with SIMD enabled. Verify you have added the code below to your project .csproj and that your publish script is using the flag `--configuration ReleaseCompat` for your compat build step.
> 
> ```
> <PropertyGroup>
>     <Configurations>Debug;Release;ReleaseCompat</Configurations>
> </PropertyGroup>
> 
> <PropertyGroup Condition=" '$(Configuration)' == 'ReleaseCompat' ">
> 	<WasmEnableSIMD>false</WasmEnableSIMD>
> 	<BlazorWebAssemblyJiterpreter>false</BlazorWebAssemblyJiterpreter>
> </PropertyGroup>
> ```
> 
> Can you share your publish script and your project .csproj file?

Yes, it worked on my iPhone 7 Plus.

**Comment by LostBeard** [comment]
> Yes, it worked on my iPhone 7 Plus.

This indicates that AOT is not the problem and that the problem is somewhere in your build procedure. I cannot tell you where the problem is exactly as you still have not given enough information to do that.

**Comment by MarkSky** [comment]
The demo is worked on my iPhone 7 Plus.
This is my .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
        <VersionPrefix>0.0.14</VersionPrefix>
        <VersionSuffix></VersionSuffix>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<RunAOTCompilation>true</RunAOTCompilation>
	</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.LocalStorage" Version="4.4.0" />
        <PackageReference Include="BlazorTurnstile" Version="2.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.0" />
        <PackageReference Include="MudBlazor" Version="6.11.1" />
        <PackageReference Include="Toolbelt.Blazor.PWA.Updater" Version="2.1.0.1" />
        <PackageReference Include="Toolbelt.Blazor.PWA.Updater.Service" Version="2.0.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\ApiServiceWithManageWeb.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
    </ItemGroup>

</Project>
```
And my dotnet cli:
`dotnet publish --nologo -c Release --property:PublishDir=bin\Publish`
`dotnet publish --nologo --no-restore -c Release --property:WasmEnableSIMD=false --property:BlazorWebAssemblyJiterpreter=false --property:PublishDir=bin\PublishCompat`
