### ISSUE TITLE
blazor already started

### ISSUE THREAD

**Issue by scarny** [LostBeard/BlazorWASMSIMDDetectExample#3]
HI,
I can't make the SIMD management work in my project (webassembly client) because when I call Blazor.start()

the system tells me that blazor has already been started... the error I get is this:

Uncaught (in promise) Error: Blazor has already started.
    at Object.Cn [as start]

how can I solve the problem.

Thank you.

**Comment by LostBeard** [comment]
You might be missing ```autostart="false"``` in the below line from your index.html which tells Blazor not to start automatically.

```<script src="_framework/blazor.webassembly.js" autostart="false"></script>```

**Comment by scarny** [comment]
A thousand thanks,
now everything works naturally.
My bad, thanks again.

**Comment by LostBeard** [comment]
Not a problem. Glad to help.
